import Head from "next/head";
import "./style.css";
import "bootstrap/dist/css/bootstrap.min.css";
import CursorAudio from "./components/commons/cursor";
import { AnimatePresence } from "framer-motion";
import UserAuthorization from "./components/userauth/userAuth";
import { AuthProvider } from "./context/AuthContext";
import CheckCookie from "./components/commons/checkCookie";





export const metadata = {
  title: "KSA | Kuwal Sanam Architekts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head> 
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <link rel="preload" href="./fonts/cg-times/Times CG.woff" as="font" type="font/woff" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/cg-times/Times CG Italic.woff" as="font" type="font/woff" crossorigin="anonymous"/>   
      <link rel="preload" href="./fonts/cg-times/Times CG Bold.woff" as="font" type="font/woff" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/cg-times/Times CG Bold Italic.woff" as="font" type="font/woff" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/avelir/AVELIRE.ttf" as="font" type="font/ttf" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/Billie Eilish/billie eilish.ttf" as="font" type="font/ttf" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/signifier/test-signifier-Extralight.woff2" as="font" type="font/woff2" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/signifier/test-signifier-Thin.woff2" as="font" type="font/woff2" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/signifier/test-signifier-Regular.woff2" as="font" type="font/woff2" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/signifier/test-signifier-Medium.woff2" as="font" type="font/woff2" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/signifier/test-signifier-Bold.woff2" as="font" type="font/woff2" crossorigin="anonymous"/>
      <link rel="preload" href="./fonts/signifier/test-signifier-Black.woff2" as="font" type="font/woff2" crossorigin="anonymous"/>

      </Head> 
      <body className="">
        <AuthProvider>
        <CursorAudio/>
        <CheckCookie/>
        <AnimatePresence mode="wait">
          {children}
        </AnimatePresence>
        </AuthProvider>
      </body>
    </html>
  );
}
