import Head from "next/head";
import "./style.css";
import "bootstrap/dist/css/bootstrap.min.css";
import CursorAudio from "./components/commons/cursor";
import { AnimatePresence } from "framer-motion";
import UserAuthorization from "./components/userauth/userAuth";





export const metadata = {
  title: "Kuwal Sanam Architeckt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head> 
      <body className="">
        <CursorAudio/>
        <UserAuthorization/>  
        <AnimatePresence mode="wait">
          {children}
        </AnimatePresence>
      </body>
    </html>
  );
}
